# Generated by Django 2.0.6 on 2019-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('starRating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('releaseDate', models.DateField()),
            ],
        ),
    ]
